
// Array with the required colors
var buttonColours = ["red","blue","green","yellow"];

//Array that stores game patterns
var gamePatter = [];

//Array that stores the buttons that were clicked
var useClickedParttener = [];

var started = false;

//2. Create a new variable called level and start at level 0.
var level = 0;

//1. Use jQuery to detect when a keyboard key has been pressed, when that happens for the first time, call nextSequence().
$(document).keypress(function() {
  if (!started) {

    //3. The h1 title starts out saying "Press A Key to Start", when the game has started, change this to say "Level 0".
    $("#level-title").text("Level " + level);
    nextSequence();
    started = true;
  }
});


//Function that generates click event on the element, specifying by id
$(".btn").click(function() {

    // get ID of clicked button
    var userChosenColour = $(this).attr("id");

    //generate pressure animation on the element
    animatePress(userChosenColour);

    //Add sound to specific element
    playSound(userChosenColour);

    // Adiciona o ID ao array
    useClickedParttener.push(userChosenColour);

     //checa o botao clicado
     checkAnswer(useClickedParttener.length -1);

    // Exibe no console para fins de depuração
    console.log("Botão clicado:", userChosenColour);    
});

//Creates pressure animation for the element received by the Name parameter
function animatePress(currentColour){

    $("#" + currentColour).addClass("pressed");

    setTimeout(function() {
        $("#" + currentColour).removeClass("pressed");
    }, 100);
}

//Adds sound to the element received by the Name parameter
function playSound(name){
    let audio = new Audio("sounds/" + name + ".mp3");
    audio.play()
}

function checkAnswer(currentyLevel) {
    if(gamePatter[currentyLevel] === useClickedParttener[currentyLevel]){

        console.log("Success");

        if(useClickedParttener.length === gamePatter.length){
            setTimeout( function(){
                nextSequence();
            }, 1000)
        }
    }else{

        console.log("Wrong");

        playSound("wrong");

        $("body").addClass("game-over");
        setTimeout(function() {
            $("body").removeClass("game-over");
        }, 1000);

        $("#level-title").text("Game over press any key to restart");
        startOver();

    }

}

function startOver(){
    //Array that stores game patterns
    gamePatter = [];

//Array that stores the buttons that were clicked
    useClickedParttener = []

started = false;

//2. Create a new variable called level and start at level 0.
 level = 0;
}

function nextSequence() {

    useClickedParttener = []

  //4. Inside nextSequence(), increase the level by 1 every time nextSequence() is called.
  level++;

  //5. Inside nextSequence(), update the h1 with this change in the value of level.
  $("#level-title").text("Level " + level);

    //Generated random sequence between 0 and 3
    let randomNumber = Math.floor(Math.random() * 4)

    //Variable that associates the colors of the array with a random number generated by the RandomNumbe
    let randomChosenColour = buttonColours[randomNumber]; 
    
    let selectElement = $("#" + randomChosenColour);
    selectElement.addClass("flash").fadeIn(100).fadeOut(100).fadeIn(100);

    playSound(randomChosenColour);

    //Add the previous color sequence to the array
    gamePatter.push(randomChosenColour);
}

console.log(level);



